name: Main

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create release & add changelog
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract release notes
        id: extract-release-notes
        uses: modum-io/extract-release-notes@v1.4.2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: MODblue ${{ github.ref }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          draft: false
          prerelease: false

  publish-npm:
    name: Publish package to NPM registry
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_CI_TOKEN}}

  publish-github:
    name: Publish package to github packages
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/

      - name: Publish to github packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  prebuild:
    name: Generates prebuilds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    needs:
      - release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_CI_TOKEN }}

      - name: Setup prebuild
        run: echo "upload=$TOKEN" > ~/.prebuildrc
        env:
          TOKEN: ${{ secrets.GH_PACKAGES_CI_TOKEN }}

      - name: Create node prebuilds
        run: npm run prebuild:node

      - name: Create electron prebuilds
        run: npm run prebuild:electron
